sudo: required
services:
  - docker

before_install:
  - docker build -t nybecmd/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true nybecmd/react-test npm test

after_success:
  - docker build -t nybound/multi-client ./client
  - docker build -t nybound/multi-nginx ./nginx
  - docker build -t nybound/multi-server ./server
  - docker build -t nybound/multi-worker ./worker

  # Log into Docker CI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # Push images to Docker Hub
  - docker push nybound/multi-client
  - docker push nybound/multi-nginx
  - docker push nybound/multi-server
  - docker push nybound/multi-worker

deploy:
  edge: true
  provider: elasticbeanstalk
  region: us-west-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-west-2-598430799738
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
